### ISSUE TITLE
Added support for Safari

### ISSUE THREAD

**Issue by BlueCocoa** [soruly/whatanime.ga-WebExtension#4]
Yet another web extension for whatanime.ga

I ported the extension to Safari on macOS, please see [BlueCocoa/WAIT-Safari](https://github.com/BlueCocoa/WAIT-Safari). (The structure is much more different from current extension for Chrome, so I didn't fork and pull this repo.)

It works good with image tags now. And as for video tags, it remains to be done. 

I was wondering if you would mind merging it to this repo to make it one of the official web extensions?

**Comment by soruly** [comment]
Thanks for the contribution ;)

I don't have a mac so I can't provide support for safari extension. Would you plan to publish your extension on Safari Extensions Gallery?

I may open a safari branch in this official repo.

**Comment by BlueCocoa** [comment]
Yes, I've submitted to Safari Extensions Gallery and now waiting for Apple.

**Comment by soruly** [comment]
Closed due to inactivity
Please reopen this issue when there is any updates.
the domain has changed to trace.moe so your extension has to update as well
