### ISSUE TITLE
Doesn't seem to do anything at all

### ISSUE THREAD

**Issue by Atario** [soruly/whatanime.ga-WebExtension#5]
I may be doing something wrong, but it doesn't look to me like the extension works at all.  Right click on image, pick "Search on whatanime.ga", absolutely nothing happens.  Tried on several different sites, all the same.

I'm on Firefox 50.1.0.

Edit:  I found it *does* do something after all:  it gives a "Failed to get search image" message in an entirely different browser window.

**Comment by soruly** [comment]
Does it not working on every website? or just for some specific websites?

**Comment by Atario** [comment]
Every site I tried it on was like this

**Comment by soruly** [comment]
Have you installed other Extensions? Would you try disabling them?
